### ISSUE TITLE
请问，可以分享一下您测试得到的定位精度吗？

### ISSUE THREAD

**Issue by SlamCabbage** [lovelyyoshino/SC-LEGO-LOAM#1]
请问您是否可以提供sc-lego-loam在kitti sequence 00-10上的测试结果？
采用EVO测试得到的绝对位姿误差APE

**Comment by SlamCabbage** [comment]
感谢您做出的精彩工作，这让我受益匪浅。

**Comment by lovelyyoshino** [comment]
你好，我并没有测试过所有的数据集
